### ISSUE TITLE
Zone Support?

### ISSUE THREAD

**Issue by ke6yjc** [dbarentine/udi-totalconnect-poly#1]
Is there any plans to enable zone support to show the status of a zone?

**Comment by dbarentine** [comment]
Yes it's on my list to add. I just haven't been able to find time to dedicate to it yet.

**Comment by ke6yjc** [comment]
Ok, will it allow real-time info from zones or just poll them every so often?

Thanks,
Ted

**Comment by dbarentine** [comment]
It will unfortunately not be real-time. It will poll on whatever the time you have set in polyglot.

The best I can tell there is no way in the current API for TC2 to get a real-time notification. It's possible they have some other undocumented API or websockets that can do it but I haven't been able to locate it. Technically the API I'm using isn't even supported or documented.

For reference this is their SOAP API that it uses: https://rs.alarmnet.com/TC21API/TC2.asmx

If someone knows of a way to hook real-time events from them I'd be glad to look at adding it.

**Comment by dbarentine** [comment]
@ke6yjc Zone support should now be in place. You can update to version 1.1.1 in the nodeserver store to get it. Let me know if you have any issues.
