### ISSUE TITLE
Log switched to Debug

### ISSUE THREAD

**Issue by macjeff** [dbarentine/udi-totalconnect-poly#10]
The latest update to polisy is causing DEBUG messages in most node servers.

Another developer fixed his. 

Yours is scrolling so fast I cant read it!!!

Here is what he said....

Just a minor thing to address the logging issue for those that update their polyglot version. The poly interface version is what set the logging to debug so I made sure to set it to error so the log won’t blow up with stuff. That’s what other nodeservers should be set to and not debug.

**Comment by macjeff** [comment]
I updated your code to fix the issue.  You can review.  I tested on Polisy and works.  

added two lines
import logging
logging.getLogger(‘urllib3’).setLevel(logging.ERROR)


[totalconnect-poly.py.zip](https://github.com/dbarentine/udi-totalconnect-poly/files/4709300/totalconnect-poly.py.zip)

**Comment by dbarentine** [comment]
@macjeff I apologize for not being more responsive. Between my day job, some COVID related issues, and now the wildfires in Oregon I have not been paying attention to these projects or the Github notifications for them.

Is this still an issue? I know you closed it but as I didn't respond originally I wanted to check with you. If it is still a problem then would you be interested in taking the code in the Zip file and just sending me a pull request for the changes?

**Comment by macjeff** [comment]
sorry it is an issue but if you install the nodeserver called (PythonTemplate) it installs a fix that fixes all of the nodeservers.   They said you can install it and then remove it after install.   But I left it for updates.  I just dont use it.   So that fix worked for me

Are you still updating this plugin?

**Comment by dbarentine** [comment]
@macjeff Yeah still updating it as I have time. Which over the last year has been very limited for open source projects. The stupid part is I just updated this node server a couple of weeks ago but forgot to include this.
