### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by craigwitter** [dbarentine/udi-totalconnect-poly#4]
Could disarming also be added? I would assume a property would need to be added for user code to do the disarm.

Thanks in advance!

**Comment by dbarentine** [comment]
@craigwitter Sorry about the delay on this. I haven't forgotten about this I just haven't had a chance to get back to it yet. But I think I'll be able to knock it out before the end of the year.

**Comment by dbarentine** [comment]
@craigwitter Sorry this took so long for me to get to. I've added it in version 1.2.0 which should be showing up in Polyglot shortly.

By default the ability to disarm is disabled. You just need to update allow_disarming to true to enable it.

**Comment by craigwitter** [comment]
Thank you. Should this work on Polyisy?

Craig

**Comment by dbarentine** [comment]
There are some dependency issues on Polisy at the moment. See Issue #5.

I've been working with UDI on it and think we are close to having a resolution. Once the dependency issue is resolved it works without issues. I'll update the other issue once we've got a fix.
