### ISSUE TITLE
Polisy Issues

### ISSUE THREAD

**Issue by macjeff** [dbarentine/udi-totalconnect-poly#5]
I see you are trying to fix.  With 1.1.2 it would say it installed but the install would never changed to installed and did not work.

In 1.1.3 it gives errors during install and the INSTALL button changes to UNINSTALL.  It also shows up but wont actually connect and work.

I would be happy to test since I am a TC 2 Alarm user and also have Envisilink 4.  I do have that working with ISY so no hurry here.

**Comment by dbarentine** [comment]
Yeah one of the dependencies is required to be compiled. And as Polisy doesn't include a compiler it was unable to complete the installation. UDI was able to build those packages for me but now it's a matter of figuring out how to get them installed as part of the nodeserver installation process.

And so far what I've tried works if I run the script manually but doesn't when run through Polyglot. Hopefully I'll have a resolution this week.

**Comment by dbarentine** [comment]
@macjeff I don't have a permanent solution yet but here is the workaround:

1. SSH into Polisy
2. Run `sudo pkg install -y py37-zeep`
3. Log into Polyglot and install the TotalConnect nodeserver

From there you should be good. Step 2 is the one that I so far can't work around. It requires sudo to run but the install.sh script isn't run that way during installation and I can't sudo within the script.

**Comment by dbarentine** [comment]
Ok so I was just able to test the permanent solution and it should all be working now. Here is the process you'll need to go through to ensure the latest packages are installed.

1. Uninstall the TotalConnect NS if you've still got it installed.
2. In Polyglot run System -> Check for Polisy Updates
3. Run System -> Update Polisy (This may not be required if your Polisy has been recently updated. But it won't hurt anything to run it anyways)
4. Reboot Polisy

Assuming that the latest Polisy updates are in place after reboot you should be able to install and start the TotalConnect NS without any issues. I've tested it locally on my Polisy and it was all working correctly as of tonight.

You can skip all of that if you've already gone through the workaround and it's already working.
