### ISSUE TITLE
No module named 'schedule'

### ISSUE THREAD

**Issue by BoomerangThree** [dbarentine/udi-totalconnect-poly#8]
Just finished installing the UDI-TotalConnect-Poly and received the following error.  Any suggestions?

2020-03-04 14:10:35,250 [MainThread] [INFO ] Received Config from STDIN.
2020-03-04 14:10:35,252 [MainThread] [INFO ] UDI Polyglot v2 Interface 2.0.34 Starting...
2020-03-04 14:10:35,256 [MainThread] [ERROR] Traceback (most recent call last):
2020-03-04 14:10:35,256 [MainThread] [ERROR] File "./totalconnect-poly.py", line 9, in <module>
2020-03-04 14:10:35,258 [MainThread] [ERROR] import schedule
2020-03-04 14:10:35,259 [MainThread] [ERROR] ModuleNotFoundError
2020-03-04 14:10:35,259 [MainThread] [ERROR] :
2020-03-04 14:10:35,260 [MainThread] [ERROR] No module named 'schedule'

**Comment by dbarentine** [comment]
@BoomerangThree was this installed in Polisy, Cloud, or some other Polyglot installation?

The dependency has been specified in both requirements.txt and requirements_cloud.txt so I'm not sure why it wasn't installed.

**Comment by BoomerangThree** [comment]
Hi dbarentine,

Yes, Local Polisy.

**Comment by dbarentine** [comment]
I'd first try uninstalling and then re-installing and see if that works. If not and you are able to SSH in it would be helpful to see the results from this command: 
cat /var/polyglot/nodeservers/TotalConnect/totalconnect-install.log

**Comment by BoomerangThree** [comment]
dbarentine,  here ya go..

Welcome to Polisy!
[admin@polisy ~]$ cat /var/polyglot/nodeservers/TotalConnect/totalconnect-install.log
Requirement already satisfied: polyinterface>=2.0.0 in /var/polyglot/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.0.34)
Collecting total-connect-client==0.50 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/0c/3a/c89d96c444ac8c41e3eb3a303850dfaf9fc4769c629ce896132038208f7b/total_connect_client-0.50.tar.gz
Collecting schedule>=0.6.0 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/57/22/3a709462eb02412bd1145f6e53604f36bba191e3e4e397bea4a718fec38c/schedule-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: paho-mqtt in /var/polyglot/.local/lib/python3.7/site-packages (from polyinterface>=2.0.0->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: python-dotenv in /var/polyglot/.local/lib/python3.7/site-packages (from polyinterface>=2.0.0->-r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: markdown2 in /var/polyglot/.local/lib/python3.7/site-packages (from polyinterface>=2.0.0->-r requirements.txt (line 1)) (2.3.8)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/site-packages (from polyinterface>=2.0.0->-r requirements.txt (line 1)) (0.10.9)
Collecting zeep (from total-connect-client==0.50->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/5e/7e/31dc5db254f4bd788f03947bae4ee38117789f2d4872a4c11a05b57700db/zeep-3.4.0-py2.py3-none-any.whl
Requirement already satisfied: attrs>=17.2.0 in /var/polyglot/.local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (2.22.0)
Requirement already satisfied: cached-property>=1.3.0 in /var/polyglot/.local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (1.5.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (2019.3)
Requirement already satisfied: requests-toolbelt>=0.7.1 in /usr/local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (0.8.0)
Collecting lxml>=3.1.0 (from zeep->total-connect-client==0.50->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/39/2b/0a66d5436f237aff76b91e68b4d8c041d145ad0a2cdeefe2c42f76ba2857/lxml-4.5.0.tar.gz
Requirement already satisfied: defusedxml>=0.4.1 in /var/polyglot/.local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: appdirs>=1.4.0 in /var/polyglot/.local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (1.4.3)
Requirement already satisfied: isodate>=0.5.4 in /var/polyglot/.local/lib/python3.7/site-packages (from zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.7.0->zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.7.0->zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.7.0->zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (1.25.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.7.0->zeep->total-connect-client==0.50->-r requirements.txt (line 2)) (2019.11.28)
Installing collected packages: lxml, zeep, total-connect-client, schedule
  Running setup.py install for lxml: started
    Running setup.py install for lxml: finished with status 'error'
    ERROR: Complete output from command /usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-yzznrzo2/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l6_lytsl/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    ERROR: Building lxml version 4.5.0.
    Building without Cython.
    ERROR: b'/bin/sh: xslt-config: not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/sax.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/cssselect.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/__init__.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/builder.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/html
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/etree_api.h -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/lxml.etree.h -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml
    copying src/lxml/includes/__init__.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/includes
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/rng
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl
    creating build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.freebsd-12.1-RELEASE-p1-amd64-3.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.freebsd-12.1-RELEASE-p1-amd64-3.7
    creating build/temp.freebsd-12.1-RELEASE-p1-amd64-3.7/src
    creating build/temp.freebsd-12.1-RELEASE-p1-amd64-3.7/src/lxml
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/include/python3.7m -c src/lxml/etree.c -o build/temp.freebsd-12.1-RELEASE-p1-amd64-3.7/src/lxml/etree.o -w
    unable to execute 'cc': No such file or directory
    Compile failed: command 'cc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit2xx8q9bn.c -o tmp/xmlXPathInit2xx8q9bn.o
    unable to execute 'cc': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-yzznrzo2/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l6_lytsl/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-yzznrzo2/lxml/
[admin@polisy ~]$

**Comment by BoomerangThree** [comment]
dbarentine, FYI, I have LIFX, MagicHome, Sonos, HarmonyHub and Yeelight installed with no issues.

**Comment by dbarentine** [comment]
@BoomerangThree you need to update Polisy. See #5 

The problem you have is one of the dependencies requires libxslt which has to be installed by Polisy prior to installing the TotalConnect NS because it's compiled.

So the install process never gets to installing the schedule dependency which is why you see the error for it missing.

**Comment by BoomerangThree** [comment]
@dbarentine done deal.  Install went successfully after installing the compiler.  Appreciate the quick and generous support.

Cheers!
